feat: EmployeeNumSearch 구현
padosori/CRA2022_7th_HelpMe pull request #9
Opened 2022-03-03 23:36 UTC by zooskin

2022-03-03 23:58 UTC, yearnotw commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +		employee_map_.insert({ "2015123099", { "2015123099", "VXIHXOTH JHOP", "VXIHXOTH", "JHOP", "010 - 3112 - 2609", "3112", "2609", "19771211", "1977", "12", "11", "CL3", "ADV" } });
DS부문 coding style에 따르면, 한 라인의 최대 character 개수가 125개로 기억합니다. 줄넘김을 통해 한 라인의 character 개수를 줄이는 건 어떠실까요?

2022-03-03 23:59 UTC, yearnotw reviewed
Format 관련하여 minor comment 남겼습니다. 라인 당 최대 character 개수를 125개로 제한하는 것 관련입니다.

2022-03-04 00:28 UTC, yearnotw approved these changes
제겐 문제 없어 보입니다.

2022-03-04 00:31 UTC, jae-yoon-cc commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +class TestEmployeeNumSearch : public ::testing::Test {
그냥 의견이긴한데 나중에 모든 테스트의 test fixture 하나로 통일했으면 합니다.

2022-03-04 00:32 UTC, jae-yoon-cc commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +public:
public: 의 위치는 맨위 아닐까요?

2022-03-04 00:32 UTC, jae-yoon-cc commented on EmployeeManager/EmployeeNumSearch.cpp
> +	if (employee_map.count(condition.value) == 1) result->push_back(employee_map[condition.value]);
세도님은 push_back 대신에 emplace_back으로 하셨는데 하나로 통일했으면 합니다.

2022-03-04 00:33 UTC, jae-yoon-cc requested changes
리뷰 남겼습니다

2022-03-04 00:40 UTC, padosori commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +class TestEmployeeNumSearch : public ::testing::Test {
Test fixture를 이와 같은 형식으로 각 Search Class마다 만드는 게 나을까요? 
아니면 공용으로 사용하는 class를 만들고, test employee_map을 setup에서 구성한 다음,
각 Search class에서 이것을 공용으로 사용하는 게 나을까요?

2022-03-04 00:44 UTC, zooskin commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +public:
public 이 필요 없어 보이네요. 삭제 하겠습니다.

2022-03-04 00:45 UTC, zooskin commented on EmployeeManager/EmployeeNumSearch.cpp
> +	if (employee_map.count(condition.value) == 1) result->push_back(employee_map[condition.value]);
emplace_back으로 통일 하겠습니다.

2022-03-04 00:54 UTC, zooskin commented on Test_EmployeeManager/TestEmployeeNumSearch.cpp
> +class TestEmployeeNumSearch : public ::testing::Test {
네 search class의 Test fixture 하나로 가져가는 것도 좋아 보입니다.
세도님 만드신 Test파일에 제 것도 추가하고 해당 test파일 삭제 하겠습니다.

2022-03-04 01:20 UTC, jae-yoon-cc approved these changes

2022-03-04 01:29 UTC, padosori approved these changes
문제없어 보입니다.

2022-03-04 01:30 UTC, merged